# Generated by Django 3.1.1 on 2020-10-09 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anônimo', max_length=80, verbose_name='Nome(Opcional)')),
                ('data_envio', models.DateTimeField(auto_now=True, verbose_name='Comentado em')),
                ('conteudo', models.TextField(max_length=300, verbose_name='Como podemos ajudá-lo?')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
            ],
            options={
                'ordering': ('-data_envio',),
            },
        ),
        migrations.CreateModel(
            name='PontoAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ponto', models.CharField(max_length=50, verbose_name='Estado')),
                ('cidade_ponto', models.CharField(max_length=50, verbose_name='Cidade')),
                ('rua_ponto', models.CharField(max_length=70, verbose_name='Rua')),
                ('numero_rua', models.CharField(max_length=70, verbose_name='Número do ponto')),
                ('referencia', models.CharField(max_length=70, verbose_name='Referência')),
                ('nome_ponto', models.CharField(max_length=70, verbose_name='Nome do ponto')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone Fixo')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='Whatsapp')),
                ('tipo_ponto', models.CharField(choices=[('PA', 'Ponto para Adoção'), ('PD', 'Ponto para Doação'), ('PDA', 'Ponto para Doação e Adoção')], max_length=20, verbose_name='Tipo do ponto')),
                ('desc_ponto', models.CharField(choices=[('ONG sem fins lucrativos', 'ONG sem fins lucrativos'), ('Casa de apoiadores', 'Casa de apoiadores')], max_length=40, verbose_name='Descrição do ponto')),
                ('imagem', models.ImageField(upload_to='points', verbose_name='Imagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coment', models.DateTimeField(auto_now=True)),
                ('autor', models.CharField(max_length=80, verbose_name='Autor')),
                ('conteudo', models.TextField(max_length=300, verbose_name='Depoimento')),
                ('permissao', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='depoiments', verbose_name='Imagem')),
                ('cadastrante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
