# Generated by Django 3.1.1 on 2020-10-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimento',
            name='titulo',
        ),
    ]
