# Generated by Django 3.0.8 on 2020-07-24 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='titulo',
            field=models.CharField(default=datetime.datetime(2020, 7, 24, 9, 43, 52, 357919, tzinfo=utc), max_length=80, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
