# Generated by Django 3.1.1 on 2020-10-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_depoimento_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='conteudo',
            field=models.TextField(max_length=400, verbose_name='Depoimento'),
        ),
        migrations.AlterField(
            model_name='pontoacesso',
            name='desc_ponto',
            field=models.CharField(choices=[('Casa de apoiadores', 'Casa de apoiadores'), ('ONG sem fins lucrativos', 'ONG sem fins lucrativos')], max_length=40, verbose_name='Descrição do ponto'),
        ),
    ]
