# Generated by Django 3.1.1 on 2020-10-08 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_contato_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoacesso',
            name='desc_ponto',
            field=models.CharField(choices=[('ONG sem fins lucrativos', 'ONG sem fins lucrativos'), ('Casa de apoiadores', 'Casa de apoiadores')], default=datetime.datetime(2020, 10, 8, 23, 41, 21, 880630, tzinfo=utc), max_length=40, verbose_name='Descrição do ponto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontoacesso',
            name='imagem',
            field=models.ImageField(default=datetime.datetime(2020, 10, 8, 23, 41, 48, 440824, tzinfo=utc), upload_to='points', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
