# Generated by Django 3.1.1 on 2020-10-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201009_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimento',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='pontoacesso',
            name='desc_ponto',
            field=models.CharField(choices=[('ONG sem fins lucrativos', 'ONG sem fins lucrativos'), ('Casa de apoiadores', 'Casa de apoiadores')], max_length=40, verbose_name='Descrição do ponto'),
        ),
    ]
