# Generated by Django 3.1.1 on 2020-10-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201008_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoacesso',
            name='numero_rua',
            field=models.CharField(max_length=70, verbose_name='Número do ponto'),
        ),
    ]
