# Generated by Django 3.1.1 on 2020-10-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201008_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoacesso',
            name='desc_ponto',
            field=models.CharField(choices=[('Casa de apoiadores', 'Casa de apoiadores'), ('ONG sem fins lucrativos', 'ONG sem fins lucrativos')], max_length=40, verbose_name='Descrição do ponto'),
        ),
        migrations.AlterField(
            model_name='pontoacesso',
            name='tipo_ponto',
            field=models.CharField(choices=[('PA', 'Ponto para Adoção'), ('PD', 'Ponto para Doação'), ('PDA', 'Ponto para Doação e Adoção')], max_length=20, verbose_name='Tipo do ponto'),
        ),
    ]
