# Generated by Django 3.1.1 on 2020-10-09 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_auto_20201009_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='cadastrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pontoacesso',
            name='desc_ponto',
            field=models.CharField(choices=[('Casa de apoiadores', 'Casa de apoiadores'), ('ONG sem fins lucrativos', 'ONG sem fins lucrativos')], max_length=40, verbose_name='Descrição do ponto'),
        ),
    ]
