# Generated by Django 3.1.1 on 2020-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201020_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoacesso',
            name='referencia',
            field=models.CharField(max_length=80, verbose_name='Referência'),
        ),
    ]
