# Generated by Django 3.0.8 on 2020-07-24 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='perfil/unknow.png', upload_to='perfil', verbose_name='Foto de Perfil')),
                ('data_de_nascimento', models.DateField(max_length=10, verbose_name='Data de nascimento')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='Whatsapp')),
                ('estado_usuario', models.CharField(max_length=50, verbose_name='Estado')),
                ('cidade_usuario', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('biografia', models.CharField(blank=True, max_length=400, verbose_name='Fale um pouco sobre você')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
