# Generated by Django 3.0.8 on 2020-07-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200724_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='perfil/unknown.png', upload_to='perfil', verbose_name='Foto de Perfil'),
        ),
    ]
