# Generated by Django 3.1.1 on 2020-10-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200724_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cidade_usuario',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
    ]
