# Generated by Django 3.0.8 on 2020-07-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo', models.TextField(max_length=300, verbose_name='Comentário')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coment', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo', models.TextField(max_length=300, verbose_name='Comentário')),
                ('aprovado', models.BooleanField(default=True)),
                ('like', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Animal')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
