# Generated by Django 3.0.8 on 2020-07-24 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_comentario_motivocadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='motivo',
            field=models.TextField(default=datetime.datetime(2020, 7, 24, 5, 42, 50, 277688, tzinfo=utc), max_length=400, verbose_name='Por que você está cadastrando esse animal?'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MotivoCadastro',
        ),
    ]
