# Generated by Django 3.1.1 on 2020-10-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20200724_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Fêmea', 'Fêmea'), ('Macho', 'Macho'), ('Sexo Desconhecido', 'Sexo Desconhecido')], max_length=18, verbose_name='Sexo'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
