# Generated by Django 3.1.1 on 2020-10-01 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20201001_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='idade',
            field=models.CharField(default=datetime.datetime(2020, 10, 1, 19, 9, 47, 433255, tzinfo=utc), max_length=40, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=8, verbose_name='Porte'),
        ),
    ]
