# Generated by Django 3.1.1 on 2020-10-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20201001_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], default='NI', max_length=20, verbose_name='Castrado'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacinado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], default='NI', max_length=20, verbose_name='Vacinado'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vermifugado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NI', 'Não Informado')], default='NI', max_length=20, verbose_name='Vermifugado'),
        ),
    ]
