# Generated by Django 3.1.1 on 2020-10-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20201001_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='motivo',
            field=models.TextField(blank=True, max_length=600, verbose_name='Por que você está cadastrando esse animal?'),
        ),
    ]
