# Generated by Django 3.1.1 on 2020-10-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20201001_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotivoDoacao',
            new_name='MotivoCadastro',
        ),
    ]
