# Generated by Django 3.1.1 on 2020-10-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20201001_2256'),
    ]

    operations = [
    ]
