# Generated by Django 3.1.1 on 2020-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20201005_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(upload_to='posts', verbose_name='Imagem'),
        ),
    ]
